config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#top'
  get 'home/about' => 'home#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users,only: [:show,:edit,:update,:index] do
  resource :relationships, only: [:create, :destroy]
  get 'follows' => 'relationships#follower', as: 'follows'
  get 'followers' => 'relationships#followed', as: 'followers'
end
resources :posts, only: [:index, :show, :edit, :create, :update, :destroy] do
    # resource :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand_name.rb
class BrandName < ApplicationRecord

end

app/models/cloth_age.rb
class ClothAge < ApplicationRecord
end

app/models/cloth_image.rb
class ClothImage < ApplicationRecord
  belongs_to :post
  attachment :image
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/made_in.rb
class MadeIn < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  # has_many :cloth_images, dependent: :destroy
  # accepts_nested_attributes_for :cloth_images, attachment: :image
  has_many_attached :cloth_images
  enum brand_name:{ "Others": 0, "Champion":1, "Pendleton":2, "POLO":3, "BIGMAC":4, "McGregor":5,
  "Fruit Of The Room":6 ,"TOWNCRAFT":7 ,"LLBean":8}
  attachment :tag_image
  # attachment :cloth_image

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   attachment :profile_image, destroy: false
   has_many :posts
   # validates :name, presence: true, length: {maximum: 10, minimum: 2}

   has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
   has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
   has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
   has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

   def follow(user_id)
     follower.create(followed_id: user_id)
   end

   # ユーザーのフォローを外す
   def unfollow(user_id)
     follower.find_by(followed_id: user_id).destroy
   end

   # フォローしていればtrueを返す
   def following?(user)
     following_user.include?(user)
   end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
  @post = Post.find(params[:post_id])
  favorite = @post.favorites.new(user_id: current_user.id)
  favorite.save

end

def destroy
  @post = Post.find(params[:post_id])
  favorite = current_user.favorites.find_by(post_id: @post.id)
  favorite.destroy
end

private
def redirect
  case params[:redirect_id].to_i
  when 0
    redirect_to posts_path
  when 1
    redirect_to post_path(@post)
  end
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!,only: [:create,:edit,:update,:destroy,:index]

  def index
    @posts = Post.all
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    screen_user(@post)
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
    else
      @posts = Post.all
      render 'index'
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_url
  end

  private
    def post_params
      params.require(:post).permit(:title, :body,:brand_name,:tag_image, cloth_images: [])
    end

    def screen_user(post)
      if post.user.id != current_user.id
        redirect_to posts_path
      end
    end

end

app/controllers/user_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :screen_user, only: [:edit, :update]

def show
  @user = User.find(params[:id])
  @posts = @user.posts
  @post = Post.new
end

def index
  @users = User.all
  @post = Post.new
end

def edit
  @user = User.find(params[:id])
end

def update
  @user = User.find(params[:id])
  if @user.update(user_params)
    redirect_to user_path(@user)
  else
    render 'edit'
  end
end

def follows

end

def followers

end

private
  def user_params
     params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def screen_user
    unless params[:id].to_i == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_user_header.html.erb
<nav class="navbar navbar-dark">
  <span class="navbar-brand">TAGNERD</span>
    <!-- ログインしている顧客 -->
    <% if user_signed_in? %>
      <ul class="nav-list">
        <li class="nav-item">
          <%= link_to "posts", posts_path, class:
          "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "About", home_about_path, class:
            "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%#= link_to "Search", , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "MyPage", user_path(current_user), class: "nav-link" %>
        </li>
      </ul>
        <!-- ログインユーザの名前 -->

        <!-- 検索フォーム -->
        <form class="form-inline nav-list">
          <input class="form-control mr-sm-1" type="search" placeholder="Search">
          <button class="btn btn-primary" type="submit">検索</button>
        </form>

    <!-- ログインしてない顧客 -->
    <% else %>
      <ul class="nav-list">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", home_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "SignIn", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "LogIn", new_user_session_path, class: "nav-link" %>
        </li>
      </ul>
      <!-- ログインユーザの名前 -->
      <span class="current_name">あ、どうも ゲストさん</span>
      <!-- 検索フォーム -->
      <form class="form-inline nav-list">
        <input class="form-control mr-sm-1" type="search" placeholder="Search">
        <button class="btn btn-primary" type="submit">検索</button>
      </form>
    <% end %>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TAGNERD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <div id="wrapper">
      <header class="navbar navbar-inverse">
        <%= render 'layouts/user_header' %>
      </header>
      <main>
          <%= yield %>
      </main>
      <footer>
        <div class="text-center">
          <p class="footer-text">© All rights recerved by SCunk.Inc.</p>
        </div>
        <!-- <div class="social">
          <i class="fa fa-facebook-square"></i>
          <i class="fa fa-twitter-square"></i>
          <i class="fa fa-instagram"></i>
        </div> -->
      </footer>
    </div>
  </body>
</html>